# -*- coding: utf-8 -*-
"""histroy chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8--nrvCDDWTX1JsQA6xCzF7xhmyglIH
"""

!pip install gradio groq

import gradio as gr
from groq import Groq
import re

# Global variables
groq_client = None
api_key_verified = False

def verify_api_key(api_key):
    """Verify if the provided API key is valid"""
    global groq_client, api_key_verified

    if not api_key or api_key.strip() == "":
        return "❌ Please enter an API key", False

    try:
        # Initialize Groq client
        groq_client = Groq(api_key=api_key.strip())

        # Test the API key with a simple request
        test_response = groq_client.chat.completions.create(
            messages=[{"role": "user", "content": "Hi"}],
            model="llama-3.3-70b-versatile",
            max_tokens=10
        )

        api_key_verified = True
        return "✅ API Key verified successfully! You can now ask about Indian history.", True

    except Exception as e:
        api_key_verified = False
        groq_client = None
        return f"❌ API Key verification failed: {str(e)}", False

def is_india_history_question(question):
    """Check if the question is related to Indian history"""

    # Keywords related to Indian history
    india_keywords = [
        'india', 'indian', 'bharat', 'hindustan', 'bharatvarsh',
        'delhi', 'mumbai', 'bengal', 'punjab', 'rajasthan', 'kerala', 'tamil',
        'gujarat', 'maharashtra', 'kashmir', 'assam', 'calcutta', 'bombay',
        'madras', 'chennai', 'kolkata'
    ]

    history_keywords = [
        'history', 'historical', 'ancient', 'medieval', 'modern',
        'empire', 'dynasty', 'king', 'queen', 'emperor', 'ruler', 'sultan',
        'maharaja', 'maharani', 'raja', 'rani', 'nawab', 'mughal', 'maratha',
        'gupta', 'maurya', 'chola', 'pallava', 'vijayanagar', 'british',
        'colonial', 'independence', 'partition', 'freedom', 'revolt',
        'war', 'battle', 'conquest', 'civilization', 'harappa', 'mohenjo',
        'vedic', 'buddhist', 'jain', 'sikh', 'gandhi', 'nehru', 'subhas',
        'bhagat', 'azad', 'patel', 'ambedkar', 'tagore', 'vivekananda',
        'ashoka', 'akbar', 'aurangzeb', 'shivaji', 'tipu', 'prithviraj',
        'chandragupta', 'harsha', 'krishnadeva', 'raja ram mohan',
        '1857', '1947', 'sepoy', 'mutiny', 'satyagraha', 'quit india',
        'swadeshi', 'salt march', 'dandi', 'jallianwala', 'rowlatt',
        'east india company', 'viceroy', 'governor general',
        'monument', 'temple', 'fort', 'palace', 'taj mahal', 'qutub',
        'red fort', 'gateway', 'ajanta', 'ellora', 'khajuraho', 'hampi',
        'vedas', 'upanishad', 'ramayana', 'mahabharata', 'arthashastra'
    ]

    question_lower = question.lower()

    # Check if question contains India-related keywords
    has_india_keyword = any(keyword in question_lower for keyword in india_keywords)

    # Check if question contains history-related keywords
    has_history_keyword = any(keyword in question_lower for keyword in history_keywords)

    # Question should have both India context and history context
    # OR have strong historical Indian terms
    return (has_india_keyword and has_history_keyword) or has_history_keyword

def chat_with_bot(message, history, api_key):
    """Main chatbot function"""
    global groq_client, api_key_verified

    # Check if API key is verified
    if not api_key_verified or groq_client is None:
        return "⚠️ Please verify your API key first using the 'Verify API Key' button."

    # Check if the question is related to Indian history
    if not is_india_history_question(message):
        return "🚫 I'm a History of India chatbot and can only answer questions related to Indian history. Please ask me about Indian historical events, empires, rulers, independence movement, ancient civilizations, or historical monuments!"

    try:
        # Prepare conversation history
        messages = [
            {
                "role": "system",
                "content": """You are an expert historian specializing in Indian history.
You provide detailed, accurate information about:
- Ancient India: Indus Valley Civilization, Vedic period, Mauryan Empire, Gupta Empire
- Medieval India: Delhi Sultanate, Mughal Empire, Vijayanagara Empire, Maratha Empire
- Colonial India: British rule, East India Company, Indian rebellions
- Indian Independence Movement: Freedom fighters, movements, key events
- Historical figures: Kings, emperors, freedom fighters, social reformers
- Historical monuments and archaeological sites
- Cultural and religious history of India
- Post-independence history of India

Provide accurate dates, names, and historical facts. Be educational and engaging.
If a question is not related to Indian history, politely inform that you only answer questions about Indian history."""
            }
        ]

        # Add conversation history
        for user_msg, bot_msg in history:
            messages.append({"role": "user", "content": user_msg})
            messages.append({"role": "assistant", "content": bot_msg})

        # Add current message
        messages.append({"role": "user", "content": message})

        # Get response from Groq
        response = groq_client.chat.completions.create(
            messages=messages,
            model="llama-3.3-70b-versatile",
            max_tokens=1500,
            temperature=0.7
        )

        return response.choices[0].message.content

    except Exception as e:
        return f"❌ Error: {str(e)}"

# Create Gradio interface
with gr.Blocks(title="History of India Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🇮🇳 History of India Chatbot")
    gr.Markdown("### Powered by Groq AI | Explore the rich history of India")

    with gr.Row():
        api_key_input = gr.Textbox(
            label="Groq API Key",
            placeholder="Enter your Groq API key here...",
            type="password",
            scale=3
        )
        verify_btn = gr.Button("Verify API Key", variant="primary", scale=1)

    api_status = gr.Textbox(label="API Status", interactive=False)

    chatbot = gr.Chatbot(label="Chat History", height=450)

    with gr.Row():
        msg = gr.Textbox(
            label="Your Question",
            placeholder="Ask me anything about Indian history...",
            scale=4
        )
        send_btn = gr.Button("Send", variant="primary", scale=1)

    clear = gr.Button("Clear Chat")

    gr.Markdown("""
    ### 📚 Example Questions You Can Ask:

    **Ancient India:**
    - Tell me about the Indus Valley Civilization
    - Who was Ashoka the Great?
    - What were the achievements of the Gupta Empire?

    **Medieval India:**
    - Describe the Mughal Empire
    - Who was Shivaji Maharaj?
    - What happened during the Delhi Sultanate?

    **Colonial Period:**
    - How did British rule begin in India?
    - What was the Revolt of 1857?
    - Tell me about the Jallianwala Bagh massacre

    **Independence Movement:**
    - What was Gandhi's role in Indian independence?
    - Explain the Quit India Movement
    - Who were the key freedom fighters?

    **Monuments & Culture:**
    - History of the Taj Mahal
    - Tell me about ancient Indian temples
    - What is the significance of Ajanta and Ellora caves?
    """)

    # Event handlers
    def verify_and_update(api_key):
        message, success = verify_api_key(api_key)
        return message

    verify_btn.click(
        verify_and_update,
        inputs=[api_key_input],
        outputs=[api_status]
    )

    msg.submit(
        chat_with_bot,
        inputs=[msg, chatbot, api_key_input],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=[msg]
    )

    send_btn.click(
        chat_with_bot,
        inputs=[msg, chatbot, api_key_input],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=[msg]
    )

    clear.click(lambda: None, None, chatbot, queue=False)

# Launch the interface
demo.launch(debug=True, share=False)

import gradio as gr
from groq import Groq
import re

# Global variables
groq_client = None
api_key_verified = False

def verify_api_key(api_key):
    """Verify if the provided API key is valid"""
    global groq_client, api_key_verified

    if not api_key or api_key.strip() == "":
        return "❌ Please enter an API key"

    try:
        # Initialize Groq client
        groq_client = Groq(api_key=api_key.strip())

        # Test the API key with a simple request
        test_response = groq_client.chat.completions.create(
            messages=[{"role": "user", "content": "Hi"}],
            model="llama-3.3-70b-versatile",
            max_tokens=10
        )

        api_key_verified = True
        return "✅ API Key verified successfully! You can now ask about Indian history."

    except Exception as e:
        api_key_verified = False
        groq_client = None
        return f"❌ API Key verification failed: {str(e)}"

def is_india_history_question(question):
    """Check if the question is related to Indian history"""

    # Keywords related to Indian history
    india_keywords = [
        'india', 'indian', 'bharat', 'hindustan', 'bharatvarsh',
        'delhi', 'mumbai', 'bengal', 'punjab', 'rajasthan', 'kerala', 'tamil',
        'gujarat', 'maharashtra', 'kashmir', 'assam', 'calcutta', 'bombay',
        'madras', 'chennai', 'kolkata'
    ]

    history_keywords = [
        'history', 'historical', 'ancient', 'medieval', 'modern',
        'empire', 'dynasty', 'king', 'queen', 'emperor', 'ruler', 'sultan',
        'maharaja', 'maharani', 'raja', 'rani', 'nawab', 'mughal', 'maratha',
        'gupta', 'maurya', 'chola', 'pallava', 'vijayanagar', 'british',
        'colonial', 'independence', 'partition', 'freedom', 'revolt',
        'war', 'battle', 'conquest', 'civilization', 'harappa', 'mohenjo',
        'vedic', 'buddhist', 'jain', 'sikh', 'gandhi', 'nehru', 'subhas',
        'bhagat', 'azad', 'patel', 'ambedkar', 'tagore', 'vivekananda',
        'ashoka', 'akbar', 'aurangzeb', 'shivaji', 'tipu', 'prithviraj',
        'chandragupta', 'harsha', 'krishnadeva', 'raja ram mohan',
        '1857', '1947', 'sepoy', 'mutiny', 'satyagraha', 'quit india',
        'swadeshi', 'salt march', 'dandi', 'jallianwala', 'rowlatt',
        'east india company', 'viceroy', 'governor general',
        'monument', 'temple', 'fort', 'palace', 'taj mahal', 'qutub',
        'red fort', 'gateway', 'ajanta', 'ellora', 'khajuraho', 'hampi',
        'vedas', 'upanishad', 'ramayana', 'mahabharata', 'arthashastra'
    ]

    question_lower = question.lower()

    # Check if question contains India-related keywords
    has_india_keyword = any(keyword in question_lower for keyword in india_keywords)

    # Check if question contains history-related keywords
    has_history_keyword = any(keyword in question_lower for keyword in history_keywords)

    # Question should have both India context and history context
    # OR have strong historical Indian terms
    return (has_india_keyword and has_history_keyword) or has_history_keyword

def chat_with_bot(message, history):
    """Main chatbot function"""
    global groq_client, api_key_verified

    # Check if API key is verified
    if not api_key_verified or groq_client is None:
        return "⚠️ Please verify your API key first using the 'Verify API Key' button."

    # Check if the question is related to Indian history
    if not is_india_history_question(message):
        return "🚫 I'm a History of India chatbot and can only answer questions related to Indian history. Please ask me about Indian historical events, empires, rulers, independence movement, ancient civilizations, or historical monuments!"

    try:
        # Prepare conversation history
        messages = [
            {
                "role": "system",
                "content": """You are an expert historian specializing in Indian history.
You provide detailed, accurate information about:
- Ancient India: Indus Valley Civilization, Vedic period, Mauryan Empire, Gupta Empire
- Medieval India: Delhi Sultanate, Mughal Empire, Vijayanagara Empire, Maratha Empire
- Colonial India: British rule, East India Company, Indian rebellions
- Indian Independence Movement: Freedom fighters, movements, key events
- Historical figures: Kings, emperors, freedom fighters, social reformers
- Historical monuments and archaeological sites
- Cultural and religious history of India
- Post-independence history of India

Provide accurate dates, names, and historical facts. Be educational and engaging.
If a question is not related to Indian history, politely inform that you only answer questions about Indian history."""
            }
        ]

        # Add conversation history
        for user_msg, bot_msg in history:
            messages.append({"role": "user", "content": user_msg})
            messages.append({"role": "assistant", "content": bot_msg})

        # Add current message
        messages.append({"role": "user", "content": message})

        # Get response from Groq
        response = groq_client.chat.completions.create(
            messages=messages,
            model="llama-3.3-70b-versatile",
            max_tokens=1500,
            temperature=0.7
        )

        return response.choices[0].message.content

    except Exception as e:
        return f"❌ Error: {str(e)}"

# Create Gradio interface
with gr.Blocks(title="History of India Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🇮🇳 History of India Chatbot")
    gr.Markdown("### Powered by Groq AI | Explore the rich history of India")

    with gr.Row():
        api_key_input = gr.Textbox(
            label="Groq API Key",
            placeholder="Enter your Groq API key here...",
            type="password",
            scale=3
        )
        verify_btn = gr.Button("Verify API Key", variant="primary", scale=1)

    api_status = gr.Textbox(label="API Status", interactive=False)

    chatbot = gr.Chatbot(label="Chat History", height=450, type="messages")

    msg = gr.Textbox(
        label="Your Question",
        placeholder="Ask me anything about Indian history...",
        lines=2
    )

    with gr.Row():
        send_btn = gr.Button("Send", variant="primary")
        clear = gr.Button("Clear Chat")

    gr.Markdown("""
    ### 📚 Example Questions You Can Ask:

    **Ancient India:**
    - Tell me about the Indus Valley Civilization
    - Who was Ashoka the Great?
    - What were the achievements of the Gupta Empire?

    **Medieval India:**
    - Describe the Mughal Empire
    - Who was Shivaji Maharaj?
    - What happened during the Delhi Sultanate?

    **Colonial Period:**
    - How did British rule begin in India?
    - What was the Revolt of 1857?
    - Tell me about the Jallianwala Bagh massacre

    **Independence Movement:**
    - What was Gandhi's role in Indian independence?
    - Explain the Quit India Movement
    - Who were the key freedom fighters?

    **Monuments & Culture:**
    - History of the Taj Mahal
    - Tell me about ancient Indian temples
    - What is the significance of Ajanta and Ellora caves?
    """)

    # Event handlers
    verify_btn.click(
        verify_api_key,
        inputs=[api_key_input],
        outputs=[api_status]
    )

    def respond(message, chat_history):
        bot_message = chat_with_bot(message, chat_history)
        chat_history.append([message, bot_message])
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    send_btn.click(respond, [msg, chatbot], [msg, chatbot])
    clear.click(lambda: None, None, chatbot, queue=False)

# Launch the interface
demo.launch(debug=True, share=False)

import gradio as gr
from groq import Groq

# Global variables
groq_client = None
api_key_verified = False

def verify_api_key(api_key):
    """Verify if the provided API key is valid"""
    global groq_client, api_key_verified

    if not api_key or api_key.strip() == "":
        return "❌ Please enter an API key"

    try:
        # Initialize Groq client
        groq_client = Groq(api_key=api_key.strip())

        # Test the API key with a simple request
        test_response = groq_client.chat.completions.create(
            messages=[{"role": "user", "content": "Hi"}],
            model="llama-3.3-70b-versatile",
            max_tokens=10
        )

        api_key_verified = True
        return "✅ API Key verified successfully! You can now ask about Indian history."

    except Exception as e:
        api_key_verified = False
        groq_client = None
        return f"❌ API Key verification failed: {str(e)}"

def is_india_history_question(question):
    """Check if the question is related to Indian history"""

    # Keywords related to Indian history
    india_keywords = [
        'india', 'indian', 'bharat', 'hindustan', 'bharatvarsh',
        'delhi', 'mumbai', 'bengal', 'punjab', 'rajasthan', 'kerala', 'tamil',
        'gujarat', 'maharashtra', 'kashmir', 'assam', 'calcutta', 'bombay',
        'madras', 'chennai', 'kolkata'
    ]

    history_keywords = [
        'history', 'historical', 'ancient', 'medieval', 'modern',
        'empire', 'dynasty', 'king', 'queen', 'emperor', 'ruler', 'sultan',
        'maharaja', 'maharani', 'raja', 'rani', 'nawab', 'mughal', 'maratha',
        'gupta', 'maurya', 'chola', 'pallava', 'vijayanagar', 'british',
        'colonial', 'independence', 'partition', 'freedom', 'revolt',
        'war', 'battle', 'conquest', 'civilization', 'harappa', 'mohenjo',
        'vedic', 'buddhist', 'jain', 'sikh', 'gandhi', 'nehru', 'subhas',
        'bhagat', 'azad', 'patel', 'ambedkar', 'tagore', 'vivekananda',
        'ashoka', 'akbar', 'aurangzeb', 'shivaji', 'tipu', 'prithviraj',
        'chandragupta', 'harsha', 'krishnadeva', 'raja ram mohan',
        '1857', '1947', 'sepoy', 'mutiny', 'satyagraha', 'quit india',
        'swadeshi', 'salt march', 'dandi', 'jallianwala', 'rowlatt',
        'east india company', 'viceroy', 'governor general',
        'monument', 'temple', 'fort', 'palace', 'taj mahal', 'qutub',
        'red fort', 'gateway', 'ajanta', 'ellora', 'khajuraho', 'hampi',
        'vedas', 'upanishad', 'ramayana', 'mahabharata', 'arthashastra'
    ]

    question_lower = question.lower()

    # Check if question contains India-related keywords
    has_india_keyword = any(keyword in question_lower for keyword in india_keywords)

    # Check if question contains history-related keywords
    has_history_keyword = any(keyword in question_lower for keyword in history_keywords)

    # Question should have both India context and history context
    # OR have strong historical Indian terms
    return (has_india_keyword and has_history_keyword) or has_history_keyword

def chat_with_bot(message, history):
    """Main chatbot function"""
    global groq_client, api_key_verified

    # Check if API key is verified
    if not api_key_verified or groq_client is None:
        return {"role": "assistant", "content": "⚠️ Please verify your API key first using the 'Verify API Key' button."}

    # Check if the question is related to Indian history
    if not is_india_history_question(message):
        return {"role": "assistant", "content": "🚫 I'm a History of India chatbot and can only answer questions related to Indian history. Please ask me about Indian historical events, empires, rulers, independence movement, ancient civilizations, or historical monuments!"}

    try:
        # Prepare conversation history
        messages = [
            {
                "role": "system",
                "content": """You are an expert historian specializing in Indian history.
You provide detailed, accurate information about:
- Ancient India: Indus Valley Civilization, Vedic period, Mauryan Empire, Gupta Empire
- Medieval India: Delhi Sultanate, Mughal Empire, Vijayanagara Empire, Maratha Empire
- Colonial India: British rule, East India Company, Indian rebellions
- Indian Independence Movement: Freedom fighters, movements, key events
- Historical figures: Kings, emperors, freedom fighters, social reformers
- Historical monuments and archaeological sites
- Cultural and religious history of India
- Post-independence history of India

Provide accurate dates, names, and historical facts. Be educational and engaging.
If a question is not related to Indian history, politely inform that you only answer questions about Indian history."""
            }
        ]

        # Add conversation history
        for msg in history:
            messages.append({"role": msg["role"], "content": msg["content"]})

        # Add current message
        messages.append({"role": "user", "content": message})

        # Get response from Groq
        response = groq_client.chat.completions.create(
            messages=messages,
            model="llama-3.3-70b-versatile",
            max_tokens=1500,
            temperature=0.7
        )

        return {"role": "assistant", "content": response.choices[0].message.content}

    except Exception as e:
        return {"role": "assistant", "content": f"❌ Error: {str(e)}"}

# Create Gradio interface
with gr.Blocks(title="History of India Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🇮🇳 History of India Chatbot")
    gr.Markdown("### Powered by Groq AI | Explore the rich history of India")

    with gr.Row():
        api_key_input = gr.Textbox(
            label="Groq API Key",
            placeholder="Enter your Groq API key here...",
            type="password",
            scale=3
        )
        verify_btn = gr.Button("Verify API Key", variant="primary", scale=1)

    api_status = gr.Textbox(label="API Status", interactive=False)

    chatbot = gr.Chatbot(label="Chat History", height=450, type="messages")

    msg = gr.Textbox(
        label="Your Question",
        placeholder="Ask me anything about Indian history...",
        lines=2
    )

    with gr.Row():
        send_btn = gr.Button("Send", variant="primary")
        clear = gr.Button("Clear Chat")

    gr.Markdown("""
    ### 📚 Example Questions You Can Ask:

    **Ancient India:**
    - Tell me about the Indus Valley Civilization
    - Who was Ashoka the Great?
    - What were the achievements of the Gupta Empire?

    **Medieval India:**
    - Describe the Mughal Empire
    - Who was Shivaji Maharaj?
    - What happened during the Delhi Sultanate?

    **Colonial Period:**
    - How did British rule begin in India?
    - What was the Revolt of 1857?
    - Tell me about the Jallianwala Bagh massacre

    **Independence Movement:**
    - What was Gandhi's role in Indian independence?
    - Explain the Quit India Movement
    - Who were the key freedom fighters?

    **Monuments & Culture:**
    - History of the Taj Mahal
    - Tell me about ancient Indian temples
    - What is the significance of Ajanta and Ellora caves?
    """)

    # Event handlers
    verify_btn.click(
        verify_api_key,
        inputs=[api_key_input],
        outputs=[api_status]
    )

    def respond(message, chat_history):
        # Add user message
        chat_history.append({"role": "user", "content": message})
        # Get bot response
        bot_message = chat_with_bot(message, chat_history[:-1])
        # Add bot message
        chat_history.append(bot_message)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    send_btn.click(respond, [msg, chatbot], [msg, chatbot])
    clear.click(lambda: [], None, chatbot, queue=False)

# Launch the interface
demo.launch(debug=True, share=False)